// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZryYkMUmpzbEEZKMHjlCqdfqLdFRvAIU',
    appId: '1:1000817192410:android:06f9869f16017a542e24e3',
    messagingSenderId: '1000817192410',
    projectId: 'thursdayfirebase-241e6',
    databaseURL: 'https://thursdayfirebase-241e6-default-rtdb.firebaseio.com',
    storageBucket: 'thursdayfirebase-241e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3MXHAZBP6XB5J9vfL3DNsTYBrvxVuBe0',
    appId: '1:1000817192410:ios:100f02527fc93bbe2e24e3',
    messagingSenderId: '1000817192410',
    projectId: 'thursdayfirebase-241e6',
    databaseURL: 'https://thursdayfirebase-241e6-default-rtdb.firebaseio.com',
    storageBucket: 'thursdayfirebase-241e6.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv-U9B0pztyceetWMsLLO4gUzjYRT63Ew',
    appId: '1:1000817192410:web:e93dc8d835a0f52f2e24e3',
    messagingSenderId: '1000817192410',
    projectId: 'thursdayfirebase-241e6',
    authDomain: 'thursdayfirebase-241e6.firebaseapp.com',
    databaseURL: 'https://thursdayfirebase-241e6-default-rtdb.firebaseio.com',
    storageBucket: 'thursdayfirebase-241e6.appspot.com',
    measurementId: 'G-Z6Q7P45SBR',
  );
}
